### ISSUE TITLE
Comments on v1

### ISSUE THREAD

**Issue by ersindemirok** [kranz-wolfe-associates/kranzwolfe.com#33]
- first page left top Kranzwolfe supposed to be Kranz Wolfe
- top bar color better to be gold of white?
- mission/organization page, are we ok with orange color
- story page, space needed between image and quote
- services page, any suggestions for lorem ipsum
- presence page icons are big and not same space inbetween
- approach page, some text needed,
- approach page, strategic target bar color not visible
- contact page, can it be same height as others
- contact page, can we add malesia contact?

- do we need to add disclaimer or some notes
- do we need to add dummy login page for clients
- do we need to add contact e-mail or form

**Comment by BartOutOfTheBox** [comment]
Thanks for the comments, Ersin.

I split up your issue into multiple smaller ones, that can be worked on individually. I think I covered all of them. Can you please check if I forgot any and then close this issue?
