### ISSUE TITLE
Story page, space needed between image and quote

### ISSUE THREAD

**Issue by BartOutOfTheBox** [kranz-wolfe-associates/kranzwolfe.com#37]
Please add some space between the image and the quotes on the story page.

**Comment by BartOutOfTheBox** [comment]
@ersindemirok please check if the current version is good? https://kranz-wolfe-associates.github.io/kranzwolfe.com/

**Comment by rainsgooi** [comment]
please check also #50, with update pictures, the margin also adjusted.
