### ISSUE TITLE
contact e-mail or form

### ISSUE THREAD

**Issue by BartOutOfTheBox** [kranz-wolfe-associates/kranzwolfe.com#46]
Currently there is no contact e-mail or form to contact us.

@ersindemirok , I would definitly add an e-mail where we can be contacted. 
- Personally I am not a big fan of a contact form. Maybe we should get some further input on this?
- When we add an e-mail address, where do we put it on the site. Can you please advice with a mockup ppt slide?

**Comment by ersindemirok** [comment]
I think one address info@kranzwolfe.com is fine at the end of each address in last slide

Best Regards,

Ersin Demirok
Business Consultant
ersin.demirok@kranzwolfe.com<mailto:ersin.demirok@kranzwolfe.com>
+905326920123
[LOGO_KWA_HOR_CMYK]
