### ISSUE TITLE
Mission section: Check updated text in v2 of mockup

### ISSUE THREAD

**Issue by BartOutOfTheBox** [kranz-wolfe-associates/kranzwolfe.com#51]

**Comment by rainsgooi** [comment]
it seems like it is already in sync with v4 mockup. should we just close this?

**Comment by BartOutOfTheBox** [comment]
The text is indeed already in sync![bitmoji](https://render.bitstrips.com/v2/cpanel/2063b3b3-2054-4a07-83b6-0a10a04de771-905f33e1-b00d-495b-b1e2-6b000bc1271f-v1.png?transparent=1&palette=1&width=246)
