### ISSUE TITLE
Delete approach page

### ISSUE THREAD

**Issue by BartOutOfTheBox** [kranz-wolfe-associates/kranzwolfe.com#53]
Delete approach page

**Comment by ersindemirok** [comment]
Hi Bart, I agree everything wouldnt be on main page.
We talked before, we need a content that enabled by password (possibly for customers) therefore may be its better to move there? updating the web ppt file accordingly .v2

**Comment by BartOutOfTheBox** [comment]
For now I'm removing the section. If needed we can always go into version control, so it's easy to bring back.
