### ISSUE TITLE
Set up DNS records for www.kranzwolfe.com to point to gh-pages

### ISSUE THREAD

**Issue by BartOutOfTheBox** [kranz-wolfe-associates/kranzwolfe.com#61]
We need to:
* set up the DNS records for www.kranzwolfe.com to point to gh-pages.
* add a CNAME file during build so that github knows the page is being served from a different url

**Comment by BartOutOfTheBox** [comment]
set up www.kranzwolfe.com as CNAME for kranz-wolfe-associates.github.io.

Telling github in the PR that it should point this repository to the domain.

**Comment by rainsgooi** [comment]
its working now.
