### ISSUE TITLE
contact emails need update

### ISSUE THREAD

**Issue by BartOutOfTheBox** [kranz-wolfe-associates/kranzwolfe.com#92]
- Make new aliasses:
  - Info.be@kranzwolfe.com 
  - Info.tr@kranzwolfe.com
  - Info.my@kranzwolfe.com 
- Use these aliasses on the website

**Comment by BartOutOfTheBox** [comment]
Updated the e-mail addres aliasses to also add 
 - Info.be@kranzwolfe.com
 - Info.tr@kranzwolfe.com
 - Info.my@kranzwolfe.com

**Comment by rainsgooi** [comment]
email address updated.
